steps:
- name: 'gcr.io/istio-io/istio-builder:0.1'
  args: ['bazel', 'run', '//mixer/docker:mixer']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'istio/mixer/docker:mixer', 'gcr.io/$PROJECT_ID/mixer:$BUILD_ID']
images:
- 'gcr.io/$PROJECT_ID/mixer'
timeout: 1800s

