---

# Whether the cluster is an Openshift (ocp) or upstream Kubernetes (k8s) cluster
cluster_flavour: ocp

# The GitHub token to use when calling GitHub's API
# The token is needed in order to avoid getting Rate Limited by GitHub's API
# Rate Limiting can easily occur in large corporate environments
# that make outgoing calls through a small range of IPs
# If the token is not set, then no API Token will be used
github_api_token: ""

istio:

  # Could be a tag "0.2.12, 0.3.0, 0.4.0" version or be empty "", then in this case, the latest release will be downloaded
  release_tag_name: "0.4.0"

  # Folder where you want to install the distro on your machine. By default, we will install it here ~/.istio
  dest: "~/.istio"

  # Install istio with or without istio-auth module
  auth: false

  # OpenShift project / Kubernetes namespace to be created
  namespace: istio-system

  addon: "{{ istio_all_addons }}"

  # Whether or not Jaeger should be installed as well
  jaeger: false

  # The names of the samples that should be installed as well.
  # The available samples are in the istio_simple_samples variable
  # In addition to the values in istio_simple_samples, 'bookinfo' can also be specified
  samples: []

  # Whether or not to open apps in the browser
  open_apps: false

  # Whether to delete resources that might exist from previous Istio installations
  delete_resources: false