version: '3'
services:

  test-backend:
    build: testmgr/test-backend
    image: test/test-backend
    restart: always
    ports:
      - 5001:5001
    networks:
      - my-network

  test-ui-dashboard:
    build: testmgr/test-ui-dashboard
    image: test/test-ui-dashboard
    restart: always
    ports:
      - 80:8082
    networks:
      - my-network

  api-server:
      build: dashboard/apiserver
      image: db/apiserver
      restart: always
      ports:
        - 18898:18898
      networks:
        - my-network

  delta-ui-dashboard:
      build: cscontrol/delta-ui-dashboard
      image: test/delta-ui-dashboard
      restart: always
      ports:
        - 8083:8083
      networks:
        - my-network

  delta-backend:
      build: cscontrol/delta-backend
      image: test/delta-backend
      restart: always
      ports:
        - 5002:5002
      networks:
        - my-network

#  firefox:
#      image: selenium/node-firefox:3.8.1-erbium
#      volumes:
#        - /dev/shm:/dev/shm
#      depends_on:
#        - hub
#      environment:
#        HUB_HOST: hub
#      networks:
#        - my-network

  chrome:
      image: selenium/node-chrome:3.11.0-californium
      volumes:
        - /dev/shm:/dev/shm
      depends_on:
        - hub
      environment:
        HUB_HOST: hub
      networks:
        - my-network

  hub:
    image: selenium/hub:3.11.0-californium
    ports:
      - 4444:4444
    networks:
      - my-network

networks:
    my-network:
      # driver: overlay
      driver: bridge

