# Openshift by default does not allow containers running with UID 0. Enable containers running with UID 0 for Istio’s service accounts
- name: Define SCC rules to enable containers running with UID zero for Istio service accounts
  shell: "{{ cmd_path }} adm policy add-scc-to-user anyuid -z {{ item }} -n istio-system"
  with_items:
    - istio-ingress-service-account
    - istio-egress-service-account
    - istio-pilot-service-account
    - istio-mixer-service-account
    - istio-ca-service-account