- name: Deploy Istio from kubernetes file
  shell: "{{ cmd_path }} create -f {{ istio_dir }}/install/kubernetes/istio.yaml"
  when: not istio.auth
  ignore_errors: true

- name: Deploy Istio Auth from kubernetes file
  shell: "{{ cmd_path }} create -f {{ istio_dir }}/install/kubernetes/istio-auth.yaml"
  when: istio.auth
  ignore_errors: true

- name: Deploy Addons defined such as Grafana, ...
  import_tasks: install_addons.yml

