# This file will result in the disabled_plugins variables being set
# The functionality is needed because some features are mutually exclusive
# (for example when Jaeger is enabled, Zipkin needs to be disabled)

- name: Set default / empty disabled addons
  set_fact:
    disabled_addons: "[]"

- name: Set zipkin disabled addon
  set_fact:
    disabled_addons: "{{ disabled_addons }} + [ 'zipkin' ]"
  when:
    - is_istioaddon_iterable
    - "'jaeger' in istio.addon"